version: '3.7'
services:
  app:
    container_name: ci-gis
    image: luqmansen/ci-gis
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - '.:/var/www/html/'
    depends_on:
      - database

  database:
    container_name: ci_gis_mysql
    image: mysql:8.0.19
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - 'mysql_volume:/var/lib/mysql'

volumes:
  mysql_volume:
